# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@thunderbird.mozilla.org\":{\"version\":\"38.5.1\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-uk@thunderbird.mozilla.org\":{\"version\":\"38.5.1\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-uk@thunderbird.mozilla.org.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "messagingmenu%40mozilla.com:1.3.1,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.5.1");
user_pref("extensions.lastAppVersion", "38.5.1");
user_pref("extensions.lastPlatformVersion", "38.5.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"messagingmenu@mozilla.com\":{\"d\":\"/usr/lib/thunderbird/extensions/messagingmenu@mozilla.com.xpi\",\"e\":true,\"v\":\"1.3.1\",\"st\":1452077584000},\"langpack-en-GB@thunderbird.mozilla.org\":{\"d\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\",\"e\":true,\"v\":\"38.5.1\",\"st\":1452078020000},\"langpack-uk@thunderbird.mozilla.org\":{\"d\":\"/usr/lib/thunderbird/extensions/langpack-uk@thunderbird.mozilla.org.xpi\",\"e\":true,\"v\":\"38.5.1\",\"st\":1452078075000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/thunderbird/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.5.1\",\"st\":1456064014000,\"mt\":1452077326000}}}");
user_pref("mail.ui-rdf.version", 11);
user_pref("mailnews.database.global.datastore.id", "a5843c78-b0b9-450c-b6a1-394ed169a6f");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Важливе");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Робоче");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Особисте");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "До виконання");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Відсунуте");
user_pref("mailnews.tags.version", 2);
user_pref("toolkit.telemetry.previousBuildID", "20160106101225");
