# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1456067246);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1456067367);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1456066886);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1456067126);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1456067006);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1456067487);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 34);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1456067017372");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1456068816372");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1456066775489");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1456070375489");
user_pref("browser.search.countryCode", "UA");
user_pref("browser.search.region", "UA");
user_pref("browser.slowStartup.averageTime", 10270);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20160209234642");
user_pref("browser.startup.homepage_override.mstone", "44.0.2");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1456153166077");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1456066831803");
user_pref("datareporting.policy.firstRunTime", "1456066766077");
user_pref("datareporting.sessions.current.activeTicks", 37);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 10529);
user_pref("datareporting.sessions.current.main", 1565);
user_pref("datareporting.sessions.current.sessionRestored", 10312);
user_pref("datareporting.sessions.current.startTime", "1456066761474");
user_pref("datareporting.sessions.current.totalTime", 1091);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"langpack-uk@firefox.mozilla.org\":{\"version\":\"44.0.2\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-uk@firefox.mozilla.org.xpi\",\"runInSafeMode\":false},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"44.0.2\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"runInSafeMode\":false},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"44.0.2\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"runInSafeMode\":false},\"firefox-hotfix@mozilla.org\":{\"version\":\"20160106.01\",\"type\":\"extension\",\"descriptor\":\"/home/volodia/.mozilla/firefox/q3u1k3cb.default/extensions/firefox-hotfix@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:44.0.2");
user_pref("extensions.getAddons.cache.lastUpdate", 1456067247);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20160106.01");
user_pref("extensions.lastAppVersion", "44.0.2");
user_pref("extensions.lastPlatformVersion", "44.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-global\":{\"langpack-uk@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-uk@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"44.0.2\",\"st\":1455064831000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"44.0.2\",\"st\":1455064750000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"44.0.2\",\"st\":1455064750000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"44.0.2\",\"st\":1456066279000,\"mt\":1455064035000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"3.2\",\"st\":1442597111000}}}");
user_pref("gecko.buildID", "20160209234642");
user_pref("gecko.mstone", "44.0.2");
user_pref("gfx.crash-guard.glcontext.appVersion", "44.0.2");
user_pref("gfx.crash-guard.glcontext.deviceID", "Mesa DRI Mobile Intel® GM45 Express Chipset ");
user_pref("gfx.crash-guard.glcontext.driverVersion", "2.1 Mesa 10.5.9");
user_pref("gfx.crash-guard.status.glcontext", 2);
user_pref("idle.lastDailyNotification", 1456067258);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1456066833);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20160209234642");
user_pref("media.gmp-manager.lastCheck", 1456066832);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1456067258);
user_pref("places.history.expiration.transient_current_max_pages", 101758);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateClearSavedPwdsOnExit", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1456067258);
user_pref("toolkit.startup.last_success", 1456066763);
user_pref("toolkit.telemetry.cachedClientID", "47729c89-26a7-4b0b-a64f-5d32e5a8c647");
user_pref("toolkit.telemetry.previousBuildID", "20160209234642");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
